### ISSUE TITLE
🤨 Conventional fixes, again.

### ISSUE THREAD

**Issue by EncryptedDev** [dmod-gg/dmod#8]
Vagabond requested me to review code, so I did 😎

Not entirely sure if you really know too much about convention as your code doesn't reflect it too well; try to Google around about it. Furthermore, there are still some unresolved issues in #5, should probably be resolved too. 

## apply.tsx
- What's the point of letting this if the value never changes?
You should only use `let` if the value is reassigned, if not `const` should be used - basic convention. 
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L17
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L59
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L42
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L38
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L34

- Merge these three lets together?
For Prettier convention, you should always merge constants to make it more readable. 
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L14-L15
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L18

-  Committing a `console.log()`?
Probably a mistake, but you should never really commit a `console.log()`
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/apply.tsx#L19

## 404.tsx
- Useless?
A button, to go to..where?
https://github.com/dmod-gg/dmod/blob/c92e33bbc79a0517d9bf58d18fed6777b6eab74d/pages/404.tsx#L9

## user/[id].tsx
Why the entire file committed out?

## api/index.ts
Is that really necessary? You should just not support that endpoint?

## api/v1/users/[id].ts
Is that really necessary? There is zero functionality to the endpoint, you should only push when its done

**Comment by MattA-Official** [comment]
While I agree with the content of this issue, I have a few issues with the context. I am currently the only web developer working on the project as part of the core team after you and @WindowsCmd left. The majority of these issues are left over from before I even joined the team. My question is: why weren't they fixed ages ago?

For you have pointed out:

1. The entire application process will be rewritten over the next few weeks
2. Already fixed on my local environment and will be available next push.
3. Commented out due to it needing rewriting and that was the quickest way to mark it as non-functional
4. I agree here, this endpoint will not be supported
5. Due to this being open source and there is currently no publicly available task tracking, the file was added to show that that file will exist. I am yet to plan out the other API routes. It would be appreciated if I could get someone who I can bounce ideas off of.

For #5 the only thing left to do is look at the styling. This will be updated as I go through the pages individually and update/write them.

The final thing I want to say is that your tone suggests I know nothing of convention, specifically:

> Not entirely sure if you really know too much about convention

Which is false as I do know conventional web development standards and as I mentioned at the beginning, almost everything listed was written before I joined the team, and while you were still on it. I reiterate my question: why didn't you fix them at an earlier point? I have made efforts to fix these things as I find them, but the workload is piling up. It would be really helpful if you could return and help fix these issues rather than just listing them.
